# Generated by Django 2.0.4 on 2018-04-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20180410_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='uname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
